### ISSUE TITLE
Support long polling

### ISSUE THREAD

**Issue by tromika** [pyrooka/metabase-cubejs-driver#17]
Datawarehouse queries could be long and run for a few minutes. So the goal is to seamlessly support long-running queries without the need of re-run those with UI actions. 
As between cube.js and Metabase the connection is over http the connection could be terminated for many reasons. Also cube.js REST API can respond with [continue wait](https://cube.dev/docs/rest-api#prerequisites-continue-wait) so somehow we should tackle this and still wait for the results.

**Comment by pyrooka** [comment]
Thanks, it's a good idea! We have to examine if we are able to override the global query timeout or not.

**Comment by pyrooka** [comment]
[These](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/async.clj#L70) are the default query timeouts (20 min for prod). I guess it's enough for us.
So the only thing we have to do is handle the Cube.js "continue wait" response.
