### ISSUE TITLE
Authentication to CubeJS production server

### ISSUE THREAD

**Issue by norbertbede** [pyrooka/metabase-cubejs-driver#22]
Hi,

this project looks me promising, thanks.
i can't find how can i setup authentication for cube.js server in metabase client.

Norbert
i would like to help test this project...assign me task if affordable.

**Comment by pyrooka** [comment]
Hi,

Thanks for the interest. I've created a new [release](https://github.com/lili-data/metabase-cubejs-driver/releases/tag/v0.3.0) with the support for Cube.js API authentication. Please check is it working fine for you.

You can help in testing by using the driver and give me feedback about how it's working. I would really appreciate it! (filtering is not implemented yet)

**Comment by norbertbede** [comment]
hi,
yes we are tested. we generate token. 

our use cases: 
1. prod mode -  connection tested by token by curl - PASS PASS (with token)
2. prod mode - test by token in metabase - your version 0..3 (with token)
3. dev mode - PASS (w/o token)

notes
- we take o look at your code, looks we are entered proper url ending with v1/
- secondly we using url https://dnsname/v1/


Exception Result
`11-13 12:59:34 ERROR sync.util :: Error running sync step: clj-http: status 403
("slingshot.support$stack_trace.invoke(support.clj:199)"
 "clj_http.client$exceptions_response.invokeStatic(client.clj:245)"
 "clj_http.client$exceptions_response.invoke(client.clj:236)"
 "clj_http.client$wrap_exceptions$fn__45350.invoke(client.clj:254)"
 "clj_http.client$wrap_accept$fn__45553.invoke(client.clj:737)"
 "clj_http.client$wrap_accept_encoding$fn__45560.invoke(client.clj:759)"
 "clj_http.client$wrap_content_type$fn__45547.invoke(client.clj:720)"
 "clj_http.client$wrap_form_params$fn__45646.invoke(client.clj:961)"
 "clj_http.client$wrap_nested_params$fn__45667.invoke(client.clj:995)"
 "clj_http.client$wrap_flatten_nested_params$fn__45676.invoke(client.clj:1019)"
 "clj_http.client$wrap_method$fn__45614.invoke(client.clj:895)"
 "clj_http.cookies$wrap_cookies$fn__44758.invoke(cookies.clj:131)"
 "clj_http.links$wrap_links$fn__45178.invoke(links.clj:63)"
 "clj_http.client$wrap_unknown_host$fn__45684.invoke(client.clj:1048)"
 "--> driver.cubejs$get_cubes.invokeStatic(cubejs.clj:39)"
 "driver.cubejs$get_cubes.invoke(cubejs.clj:35)"
 "driver.cubejs$fn__461.invokeStatic(cubejs.clj:150)"
 "driver.cubejs$fn__461.invoke(cubejs.clj:149)"
 "sync.fetch_metadata$fn__50107$db_metadata__50112$fn__50113.invoke(fetch_metadata.clj:13)"
 "sync.fetch_metadata$fn__50107$db_metadata__50112.invoke(fetch_metadata.clj:10)"
 "sync.sync_metadata.tables$fn__51575$db_metadata__51580$fn__51581.invoke(tables.clj:146)"
 "sync.sync_metadata.tables$fn__51575$db_metadata__51580.invoke(tables.clj:143)"
 "sync.sync_metadata.tables$fn__51636$sync_tables_BANG___51641$fn__51642.invoke(tables.clj:163)"
 "sync.sync_metadata.tables$fn__51636$sync_tables_BANG___51641.invoke(tables.clj:158)"
 "sync.util$fn__41836$run_step_with_metadata__41841$fn__41845$fn__41847.invoke(util.clj:356)"
 "sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
 "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
 "sync.util$fn__41836$run_step_with_metadata__41841$fn__41845.invoke(util.clj:353)"
 "sync.util$fn__41836$run_step_with_metadata__41841.invoke(util.clj:348)"
 "sync.util$fn__42028$run_sync_operation__42033$fn__42034$fn__42035.invoke(util.clj:441)"
 "sync.util$fn__42028$run_sync_operation__42033$fn__42034.invoke(util.clj:441)"
 "sync.util$fn__42028$run_sync_operation__42033.invoke(util.clj:435)"
 "sync.sync_metadata$fn__51689$sync_db_metadata_BANG___51694$fn__51695$fn__51696.invoke(sync_metadata.clj:51)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "driver$fn__18927.invokeStatic(driver.clj:673)"
 "driver$fn__18927.invoke(driver.clj:673)"
 "sync.util$sync_in_context$fn__41742.invoke(util.clj:140)"
 "sync.util$with_db_logging_disabled$fn__41739.invoke(util.clj:131)"
 "sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_logging$fn__41728.invoke(util.clj:116)"
 "sync.util$with_sync_events$fn__41723.invoke(util.clj:90)"
 "sync.util$with_duplicate_ops_prevented$fn__41714.invoke(util.clj:69)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
 "sync.util$do_sync_operation.invoke(util.clj:165)"
 "sync.sync_metadata$fn__51689$sync_db_metadata_BANG___51694$fn__51695.invoke(sync_metadata.clj:50)"
 "sync.sync_metadata$fn__51689$sync_db_metadata_BANG___51694.invoke(sync_metadata.clj:47)"
 "api.database$fn__62047$fn__62049.invoke(database.clj:521)")`


PS. if affordable we can chat or call - sure we can speak our language well (hun.) if no still ok.

norbert

**Comment by pyrooka** [comment]
Okay, let's continue this conversation on the Cube.js Slack channel. My nickname is "bn".

**Comment by norbertbede** [comment]
after release 0.4 authentication works.

**Comment by pyrooka** [comment]
Seems like it is working so I close this issue now.
