### ISSUE TITLE
Fill Metabase definitions from Cube.js descriptions

### ISSUE THREAD

**Issue by tromika** [pyrooka/metabase-cubejs-driver#27]
In cube.js you can add a description to your measures and dimensions.
![image](https://user-images.githubusercontent.com/540472/69141068-32c72080-0ac4-11ea-9078-203c828e2c5e.png)

It would be great if in Metabase these descriptions would be available automatically.
Currently it's like this:
![image](https://user-images.githubusercontent.com/540472/69141126-59855700-0ac4-11ea-8c9a-1dc608ff3d33.png)

**Comment by pyrooka** [comment]
Changed some things in PR #32 . Now it looks like this:
![Screenshot 2019-12-01 at 22 52 36](https://user-images.githubusercontent.com/15990318/69921020-bdc5f480-148e-11ea-8181-ff469b798f9c.png)

**Comment by pyrooka** [comment]
Seems like it is working, but of course you have to re-add the DB to let the driver creating new metrics with the definition from the schema.
Maybe in the future, metrics update on DB schema sync will be added.
