### ISSUE TITLE
quarter granularity not supported by Cube.js driver

### ISSUE THREAD

**Issue by norbertbede** [pyrooka/metabase-cubejs-driver#44]
Tested: Regular Quarter - absolute date - not implemented yet.

![quarter-groupby-date](https://user-images.githubusercontent.com/3862461/75087319-01d10e80-553f-11ea-998c-10ac9bcb7f61.png)

**Comment by pyrooka** [comment]
I know. Here you can find which granularities are already implemented: https://github.com/lili-data/metabase-cubejs-driver/blob/master/src/metabase/driver/cubejs/query_processor.clj#L48
