### ISSUE TITLE
Driver version 0.7 is not compatible with metabase >34.1

### ISSUE THREAD

**Issue by norbertbede** [pyrooka/metabase-cubejs-driver#46]
some breaking changes/depreciated functions broke driver.

**Comment by pyrooka** [comment]
Can you provide some more information about this? I've just built the driver with the v0.34.3 version of Metabase and seems it's working fine with the same version.

**Comment by pyrooka** [comment]
I was able to build and use the driver with the most recent Metabase version (v0.34.3) so I close this issue. Feel free to reopen if you cannot and provide some details. Thanks!
