### ISSUE TITLE
Broken beforeDate and afterDate time filters

### ISSUE THREAD

**Issue by pyrooka** [pyrooka/metabase-cubejs-driver#48]
Because we always use the `timeDimension` field for time filtering these 2 operators are not working properly anymore.
Details:

MBQL: `:filter [:> [:field-id 86] [:absolute-datetime (t/zoned-date-time 1997-01-24T00:00Z[GMT]) :default]]`

Cube.js query: `:timeDimensions [{:dimension Characters.birth, :granularity :day, :dateRange [1997-01-24T00:00:00Z]}]`

From the Cube.js docs: "If only one date specified it's equivalent to passing two same dates as a date range." 

Proposal:
Use the `timeDimension` only when 2 dates are specified and maybe if just one but with equals operator.

**Comment by igorpojzl** [comment]
Agree with the proposal i look into it.

**Comment by pyrooka** [comment]
Thank you very much!
