### ISSUE TITLE
CubeCloud Request Span Annotation

### ISSUE THREAD

**Issue by norbertbede** [pyrooka/metabase-cubejs-driver#53]
**Is your feature request related to a problem? Please describe.**
We start evaluate thanks to early access CUBE CLOUD, for compactibility rest api require some changes.
https://cube.dev/docs/rest-api#prerequisites-request-span-annotation

**Describe the solution you'd like**
implement span annotation
https://cube.dev/docs/rest-api#prerequisites-request-span-annotation

**Comment by pyrooka** [comment]
Good idea! I don't know how the `spanId` and the `requestSequenceId` should be chosen. Could you provide some information about this?

**Comment by igorpojzl** [comment]
I think `spanId` is unique for each query in `make-request` (UUID generator?). `requestSequenceId` should be sequence with first value 1000000, and incrementing with each retry of same query.

**Comment by pyrooka** [comment]
Yes, you are right! Thanks again for this!

**Comment by norbertbede** [comment]
tested on our dev build. result: works - we are going today analyse more how it works and how we can improve it if required.

**Comment by pyrooka** [comment]
Sounds good! We don't have Cube Cloud access so cannot test it and to be honest I don't really know what Cube Cloud is.
