### ISSUE TITLE
Non-date filters are not working

### ISSUE THREAD

**Issue by pyrooka** [pyrooka/metabase-cubejs-driver#54]
**Describe the bug**
Non-date filters are not working.

**To Reproduce**
Try to filter by anything, but not date.

**Expected behavior**
All filters should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/15990318/78056257-25c91080-7385-11ea-88a5-d34c43a25107.png)

**Version:**
v0.9.0

**Additional context**
This issue exists since PR #52

**Comment by igorpojzl** [comment]
I did not test this use case, sorry. PR with fix is ready.

**Comment by pyrooka** [comment]
Fixed in #55
