### ISSUE TITLE
Pulse only show table when send to slack

### ISSUE THREAD

**Issue by devtothemoon** [pyrooka/metabase-cubejs-driver#71]
**Describe the solution you'd like**
I want to send my graph to slack but when I create pulse it only shows the table not graph

**Additional context**
driver 0.13.1
metabase newest
cubejs 0.20.0

**Comment by pyrooka** [comment]
I don't know is this a driver or a Metabase error, but I'll check it out later!

**Comment by pyrooka** [comment]
Can you give more details? I have tried the Pulse with the test env and it worked well. Got this chart:
![image](https://user-images.githubusercontent.com/15990318/92286022-218dba00-ef06-11ea-904a-31a5fb02a3a0.png)

**Comment by pyrooka** [comment]
Didn't you run into some limitations? https://www.metabase.com/docs/latest/users-guide/10-pulses.html#limitations

**Comment by pyrooka** [comment]
I close this issue. Feel free to reopen is the problem still exits.
