### ISSUE TITLE
Native query bug 

### ISSUE THREAD

**Issue by Nathlmt** [pyrooka/metabase-cubejs-driver#72]
**Describe the bug**
When I use the native question it shows 
```

Input to deduplicate-cols-names does not match schema: [0;33m
 [(named [{:base_type missing-required-key, :field_ref (named [nil nil
 (named (not ("Valid field type" nil)) "field-type")]
 "Must be a valid instance of one of these clauses: :field-id, :field-literal, :joined-field, 
:fk->, :datetime-field, :expression, :binning-strategy")}] cols)] [0m

```

My query is copied from the custom question that already worked.
I tried another simple query but still don't work 

**Version:**
0.13.1
Cubejs Version: 0.20.0
Metabase version 0.36.3

**Comment by pyrooka** [comment]
Thanks for reporting this! I was able to reproduce the issue, so let's see what can I do.

**Comment by pyrooka** [comment]
[New release](https://github.com/lili-data/metabase-cubejs-driver/releases/tag/v0.13.2). No error for me, but check it please.

**Comment by Nathlmt** [comment]
Yes. It works. Thank you for your help

**Comment by pyrooka** [comment]
Thank you for the feedback!
