### ISSUE TITLE
Bug when show time in measure

### ISSUE THREAD

**Issue by devtothemoon** [pyrooka/metabase-cubejs-driver#74]
**Describe the bug**
In measures in cubejs I use min(timestamp) and in the filter, in Metabase, I choose summarize by min time and I got error: 
![image](https://user-images.githubusercontent.com/70305119/92466440-4a5dca00-f1fa-11ea-8f81-eef59d624268.png)

**Version:**
All version is lastest

**Comment by pyrooka** [comment]
Sorry but I don't understand the context. Can you attach a screenshot about your query in Metabase?

**Comment by pyrooka** [comment]
I close this issue. Feel free to reopen if the problem still exists.
